import request from 'supertest';
import { afterAll, beforeEach, describe, expect, it } from 'vitest';
import { API_BASE_PATH } from '@/config/constants';
import { ROLES } from '@/shared/constants/roles.constant';
import { getTestApp } from '../helpers/test-app';
import { disconnectDatabase, resetDatabase } from '../helpers/database';
import { authenticatedRequest } from '../helpers/auth';

/**
 * Generated by npm run generate:module. Everything below holds for any
 * generated CRUD module without foreign-key data. Add the happy path and any
 * business rules once the module has real seed data to work with — see
 * docs/adding-a-module.md Step 12.
 */

const app = getTestApp();
const CATEGORIES = `${API_BASE_PATH}/categories`;
const CATEGORY_ITEM = `${CATEGORIES}/00000000-0000-4000-8000-000000000000`;

afterAll(async () => {
  await disconnectDatabase();
});

beforeEach(async () => {
  await resetDatabase();
});

describe('Category routes — auth and validation', () => {
  it('rejects unauthenticated requests', async () => {
    await request(app).get(CATEGORIES).expect(401);
    await request(app).post(CATEGORIES).send({}).expect(401);
    await request(app).get(CATEGORY_ITEM).expect(401);
    await request(app).patch(CATEGORY_ITEM).send({}).expect(401);
    await request(app).delete(CATEGORY_ITEM).expect(401);
  });

  it('forbids a user without CATEGORY_VIEW from listing', async () => {
    const { headers } = await authenticatedRequest({ role: ROLES.USER });
    await request(app).get(CATEGORIES).set(headers).expect(403);
  });

  it('forbids a user without CATEGORY_CREATE from creating', async () => {
    const { headers } = await authenticatedRequest({ role: ROLES.USER });
    await request(app).post(CATEGORIES).set(headers).send({}).expect(403);
  });

  it('forbids a user without CATEGORY_VIEW from reading one', async () => {
    const { headers } = await authenticatedRequest({ role: ROLES.USER });
    await request(app).get(CATEGORY_ITEM).set(headers).expect(403);
  });

  it('forbids a user without CATEGORY_EDIT from updating', async () => {
    const { headers } = await authenticatedRequest({ role: ROLES.USER });
    await request(app).patch(CATEGORY_ITEM).set(headers).send({}).expect(403);
  });

  it('forbids a user without CATEGORY_DELETE from deleting', async () => {
    const { headers } = await authenticatedRequest({ role: ROLES.USER });
    await request(app).delete(CATEGORY_ITEM).set(headers).expect(403);
  });

  it('rejects an invalid create payload', async () => {
    const { headers } = await authenticatedRequest({ role: ROLES.SUPER_ADMIN });
    await request(app).post(CATEGORIES).set(headers).send({}).expect(400);
  });

  it('returns 404 for an id that does not exist', async () => {
    const { headers } = await authenticatedRequest({ role: ROLES.SUPER_ADMIN });
    await request(app).get(CATEGORY_ITEM).set(headers).expect(404);
    await request(app).patch(CATEGORY_ITEM).set(headers).send({ name: 'Sample name' }).expect(404);
    await request(app).delete(CATEGORY_ITEM).set(headers).expect(404);
  });

  it('lists with an empty result when nothing exists', async () => {
    const { headers } = await authenticatedRequest({ role: ROLES.SUPER_ADMIN });
    const response = await request(app).get(CATEGORIES).set(headers).expect(200);
    expect(response.body.data).toEqual([]);
  });

  it.todo('full create/update/delete happy path — needs foreign-key seed data for this module (see docs/adding-a-module.md Step 12)');
  it.todo('model-specific business rules, if any');
});
