import { describe, expect, it } from 'vitest';
import { Prisma } from '@/generated/prisma/client';
import { mapAccountToResponse } from '@/modules/account/account.mapper';
import type { AccountRecord } from '@/modules/account/account.types';

/**
 * Generated by npm run generate:module. The field list here is derived
 * mechanically from the Prisma model — extend it with the module's actual
 * business rules once those exist.
 */

function makeAccountRecord(overrides: Partial<AccountRecord> = {}): AccountRecord {
  return {
    id: '11111111-1111-4111-8111-111111111111',
    name: 'Sample name',
    initalBalance: new Prisma.Decimal('123.45'),
    balance: new Prisma.Decimal('123.45'),
    userId: '11111111-1111-4111-8111-111111111111',
    createdAt: new Date('2026-01-02T03:04:05.678Z'),
    updatedAt: new Date('2026-01-02T03:04:05.678Z'),
    ...overrides,
  };
}

describe('mapAccountToResponse', () => {
  it('emits exactly the documented fields', () => {
    expect(Object.keys(mapAccountToResponse(makeAccountRecord())).sort()).toEqual([
    'balance',
    'createdAt',
    'id',
    'initalBalance',
    'name',
    'updatedAt',
    'userId',
    ]);
  });

  it('maps initalBalance to a number', () => {
    const result = mapAccountToResponse(makeAccountRecord());
    expect(result.initalBalance).toBe(123.45);
  });

  it('maps balance to a number', () => {
    const result = mapAccountToResponse(makeAccountRecord());
    expect(result.balance).toBe(123.45);
  });

  it('maps createdAt to an ISO-8601 string', () => {
    const result = mapAccountToResponse(makeAccountRecord());
    expect(result.createdAt).toBe('2026-01-02T03:04:05.678Z');
  });

  it('maps updatedAt to an ISO-8601 string', () => {
    const result = mapAccountToResponse(makeAccountRecord());
    expect(result.updatedAt).toBe('2026-01-02T03:04:05.678Z');
  });
});
