import { beforeEach, describe, expect, it, vi } from 'vitest';
import { Prisma } from '@/generated/prisma/client';
import { NotFoundError } from '@/errors';
import { AccountService } from '@/modules/account/account.service';
import type { AccountRecord } from '@/modules/account/account.types';
import type { CreateAccountInput } from '@/modules/account/account.schema';

/**
 * Generated by npm run generate:module. Mocks only what the service calls —
 * see docs/testing.md. Extend with the module's actual business rules once
 * those exist; this file only proves the generated CRUD scaffolding.
 */

function createMockRepository() {
  return {
    findById: vi.fn(),
    findMany: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  };
}

function makeAccountRecord(overrides: Partial<AccountRecord> = {}): AccountRecord {
  return {
    id: '11111111-1111-4111-8111-111111111111',
    name: 'Sample name',
    initialBalance: new Prisma.Decimal('123.45'),
    balance: new Prisma.Decimal('123.45'),
    userId: '11111111-1111-4111-8111-111111111111',
    createdAt: new Date('2026-01-02T03:04:05.678Z'),
    updatedAt: new Date('2026-01-02T03:04:05.678Z'),
    ...overrides,
  };
}

const sampleInput: CreateAccountInput = {
  name: 'Sample name',
  initialBalance: 123.45,
  balance: 123.45,
  userId: '11111111-1111-4111-8111-111111111111',
};

describe('AccountService', () => {
  let repository: ReturnType<typeof createMockRepository>;
  let service: AccountService;

  beforeEach(() => {
    repository = createMockRepository();
    service = new AccountService(repository as never);
  });

  describe('getAccountById', () => {
    it('throws NotFoundError when the record does not exist', async () => {
      repository.findById.mockResolvedValue(null);
      await expect(service.getAccountById('missing-id')).rejects.toThrow(NotFoundError);
    });

    it('returns the mapped record when found', async () => {
      repository.findById.mockResolvedValue(makeAccountRecord());
      const result = await service.getAccountById('11111111-1111-4111-8111-111111111111');
      expect(result.id).toBe('11111111-1111-4111-8111-111111111111');
    });
  });

  describe('createAccount', () => {
    it('writes exactly the whitelisted fields', async () => {
      repository.create.mockResolvedValue(makeAccountRecord());
      await service.createAccount(sampleInput);
      expect(repository.create).toHaveBeenCalledWith(sampleInput);
    });
  });

  describe('updateAccount', () => {
    it('throws NotFoundError when the record does not exist', async () => {
      repository.findById.mockResolvedValue(null);
      await expect(service.updateAccount('missing-id', sampleInput)).rejects.toThrow(NotFoundError);
      expect(repository.update).not.toHaveBeenCalled();
    });

    it('writes exactly the whitelisted fields when the record exists', async () => {
      repository.findById.mockResolvedValue(makeAccountRecord());
      repository.update.mockResolvedValue(makeAccountRecord());
      await service.updateAccount('11111111-1111-4111-8111-111111111111', sampleInput);
      expect(repository.update).toHaveBeenCalledWith('11111111-1111-4111-8111-111111111111', sampleInput);
    });
  });

  describe('deleteAccount', () => {
    it('throws NotFoundError when the record does not exist', async () => {
      repository.findById.mockResolvedValue(null);
      await expect(service.deleteAccount('missing-id')).rejects.toThrow(NotFoundError);
      expect(repository.delete).not.toHaveBeenCalled();
    });
  });

  describe('listAccounts', () => {
    it('returns paginated items with meta', async () => {
      repository.findMany.mockResolvedValue({ items: [makeAccountRecord()], total: 1 });
      const result = await service.listAccounts({ page: 1, pageSize: 20, sortBy: 'createdAt', sortOrder: 'desc' });
      expect(result.accounts).toHaveLength(1);
      expect(result.meta.total).toBe(1);
    });
  });
});
