import { beforeEach, describe, expect, it, vi } from 'vitest';
import { NotFoundError } from '@/errors';
import { CategoryService } from '@/modules/category/category.service';
import type { CategoryRecord } from '@/modules/category/category.types';
import type { CreateCategoryInput } from '@/modules/category/category.schema';

/**
 * Generated by npm run generate:module. Mocks only what the service calls —
 * see docs/testing.md. Extend with the module's actual business rules once
 * those exist; this file only proves the generated CRUD scaffolding.
 */

function createMockRepository() {
  return {
    findById: vi.fn(),
    findMany: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  };
}

function makeCategoryRecord(overrides: Partial<CategoryRecord> = {}): CategoryRecord {
  return {
    id: '11111111-1111-4111-8111-111111111111',
    name: 'Sample name',
    type: 'INCOME',
    icon: 'Sample icon',
    userId: '11111111-1111-4111-8111-111111111111',
    createdAt: new Date('2026-01-02T03:04:05.678Z'),
    updatedAt: new Date('2026-01-02T03:04:05.678Z'),
    ...overrides,
  };
}

const sampleInput: CreateCategoryInput = {
  name: 'Sample name',
  type: 'INCOME',
  icon: 'Sample icon',
  userId: '11111111-1111-4111-8111-111111111111',
};

describe('CategoryService', () => {
  let repository: ReturnType<typeof createMockRepository>;
  let service: CategoryService;

  beforeEach(() => {
    repository = createMockRepository();
    service = new CategoryService(repository as never);
  });

  describe('getCategoryById', () => {
    it('throws NotFoundError when the record does not exist', async () => {
      repository.findById.mockResolvedValue(null);
      await expect(service.getCategoryById('missing-id')).rejects.toThrow(NotFoundError);
    });

    it('returns the mapped record when found', async () => {
      repository.findById.mockResolvedValue(makeCategoryRecord());
      const result = await service.getCategoryById('11111111-1111-4111-8111-111111111111');
      expect(result.id).toBe('11111111-1111-4111-8111-111111111111');
    });
  });

  describe('createCategory', () => {
    it('writes exactly the whitelisted fields', async () => {
      repository.create.mockResolvedValue(makeCategoryRecord());
      await service.createCategory(sampleInput);
      expect(repository.create).toHaveBeenCalledWith(sampleInput);
    });
  });

  describe('updateCategory', () => {
    it('throws NotFoundError when the record does not exist', async () => {
      repository.findById.mockResolvedValue(null);
      await expect(service.updateCategory('missing-id', sampleInput)).rejects.toThrow(NotFoundError);
      expect(repository.update).not.toHaveBeenCalled();
    });

    it('writes exactly the whitelisted fields when the record exists', async () => {
      repository.findById.mockResolvedValue(makeCategoryRecord());
      repository.update.mockResolvedValue(makeCategoryRecord());
      await service.updateCategory('11111111-1111-4111-8111-111111111111', sampleInput);
      expect(repository.update).toHaveBeenCalledWith('11111111-1111-4111-8111-111111111111', sampleInput);
    });
  });

  describe('deleteCategory', () => {
    it('throws NotFoundError when the record does not exist', async () => {
      repository.findById.mockResolvedValue(null);
      await expect(service.deleteCategory('missing-id')).rejects.toThrow(NotFoundError);
      expect(repository.delete).not.toHaveBeenCalled();
    });
  });

  describe('listCategories', () => {
    it('returns paginated items with meta', async () => {
      repository.findMany.mockResolvedValue({ items: [makeCategoryRecord()], total: 1 });
      const result = await service.listCategories({ page: 1, pageSize: 20, sortBy: 'createdAt', sortOrder: 'desc' });
      expect(result.categorys).toHaveLength(1);
      expect(result.meta.total).toBe(1);
    });
  });
});
