import { describe, expect, it } from 'vitest';
import { mapCategoryToResponse } from '@/modules/category/category.mapper';
import type { CategoryRecord } from '@/modules/category/category.types';

/**
 * Generated by npm run generate:module. The field list here is derived
 * mechanically from the Prisma model — extend it with the module's actual
 * business rules once those exist.
 */

function makeCategoryRecord(overrides: Partial<CategoryRecord> = {}): CategoryRecord {
  return {
    id: '11111111-1111-4111-8111-111111111111',
    name: 'Sample name',
    type: 'INCOME',
    icon: 'Sample icon',
    userId: '11111111-1111-4111-8111-111111111111',
    createdAt: new Date('2026-01-02T03:04:05.678Z'),
    updatedAt: new Date('2026-01-02T03:04:05.678Z'),
    ...overrides,
  };
}

describe('mapCategoryToResponse', () => {
  it('emits exactly the documented fields', () => {
    expect(Object.keys(mapCategoryToResponse(makeCategoryRecord())).sort()).toEqual([
    'createdAt',
    'icon',
    'id',
    'name',
    'type',
    'updatedAt',
    'userId',
    ]);
  });

  it('maps createdAt to an ISO-8601 string', () => {
    const result = mapCategoryToResponse(makeCategoryRecord());
    expect(result.createdAt).toBe('2026-01-02T03:04:05.678Z');
  });

  it('maps updatedAt to an ISO-8601 string', () => {
    const result = mapCategoryToResponse(makeCategoryRecord());
    expect(result.updatedAt).toBe('2026-01-02T03:04:05.678Z');
  });

  it('maps a null icon to null', () => {
    const result = mapCategoryToResponse(makeCategoryRecord({ icon: null }));
    expect(result.icon).toBeNull();
  });
});
