import { describe, expect, it } from 'vitest';
import { Prisma } from '@/generated/prisma/client';
import { mapExpenseToResponse } from '@/modules/expense/expense.mapper';
import type { ExpenseRecord } from '@/modules/expense/expense.types';

/**
 * Generated by npm run generate:module. The field list here is derived
 * mechanically from the Prisma model — extend it with the module's actual
 * business rules once those exist.
 */

function makeExpenseRecord(overrides: Partial<ExpenseRecord> = {}): ExpenseRecord {
  return {
    id: '11111111-1111-4111-8111-111111111111',
    title: 'Sample title',
    description: 'Sample description',
    amount: new Prisma.Decimal('123.45'),
    date: new Date('2026-01-02T03:04:05.678Z'),
    categoryId: '11111111-1111-4111-8111-111111111111',
    userId: '11111111-1111-4111-8111-111111111111',
    createdAt: new Date('2026-01-02T03:04:05.678Z'),
    updatedAt: new Date('2026-01-02T03:04:05.678Z'),
    ...overrides,
  };
}

describe('mapExpenseToResponse', () => {
  it('emits exactly the documented fields', () => {
    expect(Object.keys(mapExpenseToResponse(makeExpenseRecord())).sort()).toEqual([
    'amount',
    'categoryId',
    'createdAt',
    'date',
    'description',
    'id',
    'title',
    'updatedAt',
    'userId',
    ]);
  });

  it('maps amount to a number', () => {
    const result = mapExpenseToResponse(makeExpenseRecord());
    expect(result.amount).toBe(123.45);
  });

  it('maps date to an ISO-8601 string', () => {
    const result = mapExpenseToResponse(makeExpenseRecord());
    expect(result.date).toBe('2026-01-02T03:04:05.678Z');
  });

  it('maps createdAt to an ISO-8601 string', () => {
    const result = mapExpenseToResponse(makeExpenseRecord());
    expect(result.createdAt).toBe('2026-01-02T03:04:05.678Z');
  });

  it('maps updatedAt to an ISO-8601 string', () => {
    const result = mapExpenseToResponse(makeExpenseRecord());
    expect(result.updatedAt).toBe('2026-01-02T03:04:05.678Z');
  });

  it('maps a null description to null', () => {
    const result = mapExpenseToResponse(makeExpenseRecord({ description: null }));
    expect(result.description).toBeNull();
  });
});
