import { beforeEach, describe, expect, it, vi } from 'vitest';
import { Prisma } from '@/generated/prisma/client';
import { NotFoundError } from '@/errors';
import { ExpenseService } from '@/modules/expense/expense.service';
import type { ExpenseRecord } from '@/modules/expense/expense.types';
import type { CreateExpenseInput } from '@/modules/expense/expense.schema';

/**
 * Generated by npm run generate:module. Mocks only what the service calls —
 * see docs/testing.md. Extend with the module's actual business rules once
 * those exist; this file only proves the generated CRUD scaffolding.
 */

function createMockRepository() {
  return {
    findById: vi.fn(),
    findMany: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  };
}

function makeExpenseRecord(overrides: Partial<ExpenseRecord> = {}): ExpenseRecord {
  return {
    id: '11111111-1111-4111-8111-111111111111',
    title: 'Sample title',
    description: 'Sample description',
    amount: new Prisma.Decimal('123.45'),
    date: new Date('2026-01-02T03:04:05.678Z'),
    categoryId: '11111111-1111-4111-8111-111111111111',
    userId: '11111111-1111-4111-8111-111111111111',
    createdAt: new Date('2026-01-02T03:04:05.678Z'),
    updatedAt: new Date('2026-01-02T03:04:05.678Z'),
    ...overrides,
  };
}

const sampleInput: CreateExpenseInput = {
  title: 'Sample title',
  description: 'Sample description',
  amount: 123.45,
  date: new Date('2026-01-02T03:04:05.678Z'),
  categoryId: '11111111-1111-4111-8111-111111111111',
  userId: '11111111-1111-4111-8111-111111111111',
};

describe('ExpenseService', () => {
  let repository: ReturnType<typeof createMockRepository>;
  let service: ExpenseService;

  beforeEach(() => {
    repository = createMockRepository();
    service = new ExpenseService(repository as never);
  });

  describe('getExpenseById', () => {
    it('throws NotFoundError when the record does not exist', async () => {
      repository.findById.mockResolvedValue(null);
      await expect(service.getExpenseById('missing-id')).rejects.toThrow(NotFoundError);
    });

    it('returns the mapped record when found', async () => {
      repository.findById.mockResolvedValue(makeExpenseRecord());
      const result = await service.getExpenseById('11111111-1111-4111-8111-111111111111');
      expect(result.id).toBe('11111111-1111-4111-8111-111111111111');
    });
  });

  describe('createExpense', () => {
    it('writes exactly the whitelisted fields', async () => {
      repository.create.mockResolvedValue(makeExpenseRecord());
      await service.createExpense(sampleInput);
      expect(repository.create).toHaveBeenCalledWith(sampleInput);
    });
  });

  describe('updateExpense', () => {
    it('throws NotFoundError when the record does not exist', async () => {
      repository.findById.mockResolvedValue(null);
      await expect(service.updateExpense('missing-id', sampleInput)).rejects.toThrow(NotFoundError);
      expect(repository.update).not.toHaveBeenCalled();
    });

    it('writes exactly the whitelisted fields when the record exists', async () => {
      repository.findById.mockResolvedValue(makeExpenseRecord());
      repository.update.mockResolvedValue(makeExpenseRecord());
      await service.updateExpense('11111111-1111-4111-8111-111111111111', sampleInput);
      expect(repository.update).toHaveBeenCalledWith('11111111-1111-4111-8111-111111111111', sampleInput);
    });
  });

  describe('deleteExpense', () => {
    it('throws NotFoundError when the record does not exist', async () => {
      repository.findById.mockResolvedValue(null);
      await expect(service.deleteExpense('missing-id')).rejects.toThrow(NotFoundError);
      expect(repository.delete).not.toHaveBeenCalled();
    });
  });

  describe('listExpenses', () => {
    it('returns paginated items with meta', async () => {
      repository.findMany.mockResolvedValue({ items: [makeExpenseRecord()], total: 1 });
      const result = await service.listExpenses({ page: 1, pageSize: 20, sortBy: 'createdAt', sortOrder: 'desc' });
      expect(result.expenses).toHaveLength(1);
      expect(result.meta.total).toBe(1);
    });
  });
});
